project:
  name: quickstart-grid-connect-connectsense
  owner: quickstart-eng@amazon.com
  s3_regional_buckets: True
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  regions:
    - af-south-1
    - ap-east-1
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - eu-south-1
    - eu-north-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - me-south-1
    - sa-east-1
tests:
  grid-connect-connectsense:
    parameters:
      QSS3BucketName: "$[taskcat_autobucket]"
    template: templates/connect-sense.template.yaml
    regions: # no availability of AWS::IoTAnalytics in other regions
      - us-east-1
#      - us-west-2
#      - ap-southeast-2
#      - eu-central-1
#      - eu-west-1

  grid-connect-sitewise:
    parameters:
      QSS3BucketName: "$[taskcat_autobucket]"
    template: templates/sitewise-ml.template.yaml
    regions: # no availability of AWS::IoTAnalytics in other regions
      - us-east-1
#      - us-west-2
#      - ap-southeast-2
#      - eu-central-1
#      - eu-west-1